#!/bin/bash
print ()
{
	echo
	echo $1
}

if [ `whoami` != 'root' ]; then print "You must run this script as root!";
	exit;
fi;

ask_continue ()
{
	print "Press enter to continue"
	read PROCEED
}

TARGET="/usr/local/aptlocal"
DIR=`pwd`

print "APTLOCAL INSTALLER ver 1.0"
print "The installer is running in:"
print $DIR
print "This directory will be linked to - ${TARGET}"


ask_continue


print "Initializing..."
print "Removing if exists:"
echo "$TARGET"
print
rm "$TARGET"
echo "Done."

print "Linking current directory to ${TARGET}"
ln -s -f "$DIR" "$TARGET"
echo "Done"

print "Creating folders..."
mkdir -p repo/debs scripts/config
echo "Done."








echo "Generating Aptlocal Script";
cat > scripts/aptlocal <<EOF
#!/bin/bash
DIR="${TARGET}/repo";
cd "\${DIR}"
echo "Running in <\`pwd\`>";

copy_debs ()
{
    echo
    echo "Copying Packages...";
    cp -u -f /var/cache/apt/archives/*.deb debs;
}





gen_packages_gz ()
{
    echo "Generating index of packages...";
    apt-ftparchive packages debs > Packages;
    gzip -k -f Packages;

}



clean_repo ()
{
    rm -fr  Packages.gz Packages;
}



OPTIONS=(
"Copy-Packages"
"Build-Repo"
"Exit"
)


PS3="What to do:"
select OPT in  \${OPTIONS[@]};
    do
        case \$OPT in
        \${OPTIONS[0]})
        copy_debs
        break
        ;;
        \${OPTIONS[1]})
        copy_debs
        clean_repo
        gen_packages_gz
        echo "Now run: apt-get update"
        break
        ;;
        \${OPTIONS[2]})
        exit
        break
        ;;
        esac
done


echo "Done..";
EOF
chmod 755 scripts/aptlocal


# Linking script
echo  "Linking Scripts...";
ln -s -f "$TARGET/scripts/aptlocal" /usr/local/bin




# Generating repository
print "Generating Repository...";
cat > scripts/config/aptlocal.list <<EOF
deb [trusted=yes] file:${TARGET}/repo ./
EOF
echo "Adding Repository"
cp scripts/config/aptlocal.list /etc/apt/sources.list.d



# Installation complete
print "Installation complete!"
ask_continue

print "You can now run: aptlocal"
echo "Use this to manage your repository"

print "Always use apt-get so that the packages you download from other"
echo "repositories are not deleted before you copy them to the local repository!"

ask_continue
echo
