#!/bin/bash
print_line ()
{
    echo "===============================";
    echo
}

SCRIPT_ROOT="$(dirname "$(realpath "$0")")";
REPO_ROOT="$(realpath "$SCRIPT_ROOT/../")";

cd "$REPO_ROOT/repo"


copy_debs ()
{
    print_line
    echo "Copying Packages...";
    cp -u -f /var/cache/apt/archives/*.deb debs;
}


start_server ()
{
    print_line
    echo "Starting Server...";
    node "$SCRIPT_ROOT/server.js";
}


delete_old_packages()
{
    print_line
    echo "Removing old packages...";
	node "$SCRIPT_ROOT/clean.js";
	
	print_line
    echo "Creating archive";
	gzip -k -f Packages;
}



build_repo ()
{	
	copy_debs
	echo "Generating index of packages...";
	apt-ftparchive packages debs > Packages;


    delete_old_packages
    
    

	echo "===============================";
    echo "Now run: 'apt-get update'";
}



OPTIONS=(
"Start-Server"
"Copy-Packages"
"Build-Repo"
"Delete-Old-Packages"
"Exit"
)


PS3="What to do:"
select OPT in  ${OPTIONS[@]};
    do
        case $OPT in
        ${OPTIONS[0]})
        start_server
        break
        ;;
        ${OPTIONS[1]})
        copy_debs
        break
        ;;
        ${OPTIONS[2]})
		build_repo
        break
        ;;
        ${OPTIONS[3]})
		delete_old_packages
        break
        ;;
        ${OPTIONS[4]})
        exit
        break
        ;;
        esac
done


echo "Done..";
